export const COURSE_TYPES = {
    SINGLE: "SINGLE",
    SERIES: "SERIES"
}

export const COURSE_DETAIL_TYPES = {
    OBJECTIVE: "OBJECTIVE",
    INFORMATION: "INFORMATION",
    INSTRUCTOR: "INSTRUCTOR"
}